package kiinse.plugin.somnium.files.config;

import kiinse.plugins.api.darkwaterapi.files.config.interfaces.ConfigKeys;

public enum Config implements ConfigKeys {
    NIGHT_SKIP_ENABLED,
    NIGHT_SKIP_PERCENTAGE,
    NIGHT_SKIP_TIME_RATE,
    NIGHT_SKIP_DAYTIME_TICKS,
    NIGHT_SKIP_INSTANT_SKIP,
    NIGHT_SKIP_PROPORTIONAL_ACCELERATION,
    NIGHT_SKIP_CLEAR_RAIN,
    NIGHT_SKIP_CLEAR_THUNDER,
    NIGHT_SKIP_CLEAR_PHANTOM_STATISTIC,
    EXCLUSIONS_IGNORED_PERMISSION,
    EXCLUSIONS_EXCLUDE_SURVIVAL,
    EXCLUSIONS_EXCLUDE_ADVENTURE,
    EXCLUSIONS_EXCLUDE_CREATIVE,
    EXCLUSIONS_EXCLUDE_SPECTATOR,
    EXCLUSIONS_EXCLUDE_VANISHED,
    EXCLUSIONS_EXCLUDE_AFK,
    AFK_DETECTION_ENABLED,
    AFK_DETECTION_TIMEOUT,
    BLACKLISTED_WORLDS,
    WHITELIST_MODE,
    MESSAGES_CHAT_ENABLED,
    MESSAGES_CHAT_COOLDOWN,
    MESSAGES_ACTIONBAR_ENABLED,
    MESSAGES_BOSSBAR_ENABLED,
    MESSAGES_BOSSBAR_SLEEPING_MESSAGE,
    MESSAGES_BOSSBAR_SLEEPING_COLOR,
    MESSAGES_BOSSBAR_SKIPPING_MESSAGE,
    MESSAGES_BOSSBAR_SKIPPING_COLOR,
    VERSION,
    INTERVAL,
    DEBUG

}
